---
kind: template
load: docker-build-multiarch.yaml
data:
  dockerfiledir: ./Dockerfile 
  buildcontext: latest/
  imagename: app/plex-media-server
  hubimagename: plex-media-server
  giturl: ''
  gitbranch: ''
  repotype: both
  imagetag: latest  
  branches: ['master', 'main']
# ---
# kind: template
# load: docker-build-multiarch.yaml
# data:
#   dockerfiledir: ./autoupdate
#   imagename: plex-media-server
#   imagetag: autoupdate  
