---
kind: template
load: docker-build-multiarch.yaml
data:
  dockerfiledir: ./latest
  imagename: plex-media-server
  imagetag: latest  
  branches: ['master', 'main']
# ---
# kind: template
# load: docker-build-multiarch.yaml
# data:
#   dockerfiledir: ./autoupdate
#   imagename: plex-media-server
#   imagetag: autoupdate  
